FROM python:3.5

RUN apt-get update

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN pip install --upgrade pip -i https://pypi.douban.com/simple
COPY . /usr/src/app/

RUN python3 setup.py install
RUN unichain -y configure